language: ruby
rvm:
- 2.3.3
before_script:
- chmod +x ./script/cibuild.sh
script: "./script/cibuild.sh"
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
exclude:
- vendor
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_fc90e8e05e8e_key -iv $encrypted_fc90e8e05e8e_iv
  -in deploy_rsa.enc -out deploy_rsa -d
